const express = require('express');
const router = express.Router();
const c = require('../controllers/purchaseOrderController');
const { protect, authorize } = require('../middleware/auth');
router.use(protect);
router.route('/').get(c.getAll).post(c.create);
router.route('/:id').get(c.getOne).put(c.update).delete(c.remove);
router.put('/:id/send', c.send);
router.put('/:id/receive', c.receive);
router.put('/:id/cancel', c.cancel);
router.post('/:id/create-bill', c.createBill);
module.exports = router;
