const Expense = require('../models/Expense');
const userFilter = (req) => req.user.role === 'admin' ? {} : { createdBy: req.user._id };
const gen = async () => { const l = await Expense.findOne().sort({ createdAt: -1 }); const n = l ? parseInt(l.expenseNumber.replace('EXP-', '')) + 1 : 1; return `EXP-${String(n).padStart(4, '0')}`; };

exports.getAll = async (req, res, next) => { try { const { status } = req.query; const f = { ...userFilter(req) }; if (status) f.status = status; const d = await Expense.find(f).populate('vendor', 'name').populate('createdBy', 'name').sort({ createdAt: -1 }); res.json({ success: true, data: d }); } catch (e) { next(e); } };
exports.getOne = async (req, res, next) => { try { const d = await Expense.findOne({ _id: req.params.id, ...userFilter(req) }).populate('vendor', 'name').populate('createdBy', 'name'); if (!d) return res.status(404).json({ success: false, message: 'Not found' }); res.json({ success: true, data: d }); } catch (e) { next(e); } };
exports.create = async (req, res, next) => { try { const expenseNumber = await gen(); const d = await Expense.create({ ...req.body, expenseNumber, createdBy: req.user._id }); res.status(201).json({ success: true, data: d }); } catch (e) { next(e); } };
exports.update = async (req, res, next) => { try { const d = await Expense.findOneAndUpdate({ _id: req.params.id, ...userFilter(req) }, req.body, { new: true, runValidators: true }); if (!d) return res.status(404).json({ success: false, message: 'Not found' }); res.json({ success: true, data: d }); } catch (e) { next(e); } };
exports.remove = async (req, res, next) => { try { const d = await Expense.findOne({ _id: req.params.id, ...userFilter(req) }); if (!d) return res.status(404).json({ success: false, message: 'Not found' }); await d.deleteOne(); res.json({ success: true, message: 'Deleted' }); } catch (e) { next(e); } };
exports.approve = async (req, res, next) => { try { const d = await Expense.findOne({ _id: req.params.id, ...userFilter(req) }); if (!d) return res.status(404).json({ success: false, message: 'Not found' }); d.status = 'approved'; await d.save(); res.json({ success: true, data: d }); } catch (e) { next(e); } };
exports.markPaid = async (req, res, next) => { try { const d = await Expense.findOne({ _id: req.params.id, ...userFilter(req) }); if (!d) return res.status(404).json({ success: false, message: 'Not found' }); d.status = 'paid'; d.paymentMethod = req.body.paymentMethod || ''; await d.save(); res.json({ success: true, data: d }); } catch (e) { next(e); } };
