const RetainerInvoice = require('../models/RetainerInvoice');
const userFilter = (req) => req.user.role === 'admin' ? {} : { createdBy: req.user._id };
const gen = async () => { const l = await RetainerInvoice.findOne().sort({ createdAt: -1 }); const n = l ? parseInt(l.retainerNumber.replace('RET-', '')) + 1 : 1; return `RET-${String(n).padStart(4, '0')}`; };

exports.getAll = async (req, res, next) => { try { const { status } = req.query; const f = { ...userFilter(req) }; if (status) f.status = status; const d = await RetainerInvoice.find(f).populate('customer', 'name email').populate('createdBy', 'name').sort({ createdAt: -1 }); res.json({ success: true, data: d }); } catch (e) { next(e); } };
exports.getOne = async (req, res, next) => { try { const d = await RetainerInvoice.findOne({ _id: req.params.id, ...userFilter(req) }).populate('customer', 'name email phone company').populate('createdBy', 'name'); if (!d) return res.status(404).json({ success: false, message: 'Not found' }); res.json({ success: true, data: d }); } catch (e) { next(e); } };
exports.create = async (req, res, next) => { try { const retainerNumber = await gen(); const d = await RetainerInvoice.create({ ...req.body, retainerNumber, createdBy: req.user._id }); res.status(201).json({ success: true, data: d }); } catch (e) { next(e); } };
exports.update = async (req, res, next) => { try { const d = await RetainerInvoice.findOneAndUpdate({ _id: req.params.id, ...userFilter(req) }, req.body, { new: true, runValidators: true }); if (!d) return res.status(404).json({ success: false, message: 'Not found' }); res.json({ success: true, data: d }); } catch (e) { next(e); } };
exports.remove = async (req, res, next) => { try { const d = await RetainerInvoice.findOne({ _id: req.params.id, ...userFilter(req) }); if (!d) return res.status(404).json({ success: false, message: 'Not found' }); if (d.status === 'paid') return res.status(400).json({ success: false, message: 'Cannot delete paid retainer' }); await d.deleteOne(); res.json({ success: true, message: 'Deleted' }); } catch (e) { next(e); } };
exports.markPaid = async (req, res, next) => { try { const d = await RetainerInvoice.findOne({ _id: req.params.id, ...userFilter(req) }); if (!d) return res.status(404).json({ success: false, message: 'Not found' }); d.status = 'paid'; d.paymentMethod = req.body.paymentMethod || ''; await d.save(); res.json({ success: true, data: d }); } catch (e) { next(e); } };
exports.send = async (req, res, next) => { try { const d = await RetainerInvoice.findOne({ _id: req.params.id, ...userFilter(req) }); if (!d) return res.status(404).json({ success: false, message: 'Not found' }); d.status = 'sent'; await d.save(); res.json({ success: true, data: d }); } catch (e) { next(e); } };
